#!/usr/bin/ruby --disable-gems
# Disable gems by default because they slow down startup

require 'shellwords'
def se str
  Shellwords.shellescape str
end

if ARGV.size == 3
  friendly = ARGV.shift
  profile = ARGV.shift
  url = ARGV.shift
elsif 
  friendly = ARGV.shift
  profile = friendly.downcase
  url = "https://www.#{profile}.com"
else
  abort "Usage: apple-pie [friendly name] [url] [profile]"
end

name = url.gsub /[^\w\.]/, '_'

window_class = name.sub /^https?___/, ''

desktop_file = "#{ENV['HOME']}/.local/share/applications/chrome-#{name}.desktop"

contents = <<HERE
#!/usr/bin/env xdg-open
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=#{friendly}
Exec=/usr/bin/chromium-browser --user-data-dir=#{ENV['HOME']}/.cache/apple-pie/#{se profile} --app=#{se url}
Icon=chrome-#{name}
StartupWMClass=#{window_class}
HERE

if !File.exists?(desktop_file) || File.read(desktop_file) != contents
  File.binwrite desktop_file, contents
  File.chmod 0755, desktop_file
end

icon_file = "#{ENV['HOME']}/.local/share/icons/hicolor/256x256/apps/chrome-#{name}.png"
unless File.exists?(icon_file)
  require 'rubygems'
  require 'pismo'
  icon_url = Pismo::Document.new( url ).favicon
  icon_name = "/tmp/chrome-app-icon/#{File.basename( icon_url )}"
  FileUtils.mkdir_p "/tmp/chrome-app-icon"
  system "wget -O #{se icon_name} #{se icon_url}"
  abort "Can't fetch #{icon_url}" unless $? == 0
  system "convert #{se icon_name} -resize 256x256 -composite -depth 8 #{se icon_file}"
  abort "Can't convert #{icon_name}" unless $? == 0
end

system "xdotool search --classname #{se window_class} windowactivate"

exit 0 if $? == 0

system "gtk-launch chrome-#{name}"

abort "Can't gtk-launch chrome-#{name}" unless $? == 0
